server:
  port: 8080
  servlet:
    context-path: /project

spring:
  servlet:
    multipart: 
      max-file-size: 5120MB
      max-request-size: 5120MB
  mvc:
    servlet:
      load-on-startup: 1
  server:
    datasource:
      url: jdbc:mysql://localhost:3306/project_fs?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
      username: root
      password: 2wsx3edc
      driverClassName: com.mysql.jdbc.Driver
    projectFilePath: /home/project/file
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
logging:
  config: classpath:log4j2.xml        